name: dagger
on:
  push:
    branches: [main]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.21"
      - name: Install Dagger
        uses: dagger/dagger-for-github@v4
        with:
          install-only: true
      - name: Run Dagger pipeline
        run: dagger run go run ci/main.go
